name: Markdown

on:
  workflow_call:
    inputs:
      md-lint:
        description: 'Path to the markdown configuration file'
        required: true
        default: '.github/config/markdown.yml'
        type: string
      md-ignore:
        description: 'Path to the markdown ignore file'
        required: true
        default: '.github/config/markdownignore'
        type: string
      spellcheck:
        description: 'Path to the spellcheck configuration file'
        required: true
        default: '.github/config/spellcheck.yml'
        type: string

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Lint Markdown
    steps:
      - uses: actions/checkout@v4
      - name: Markdown Linting
        uses: nosborn/github-action-markdown-cli@v3
        with:
          files: .
          dot: true
          config_file: ${{ inputs.md-lint }}
          ignore_path: ${{ inputs.md-ignore }}
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          config_path: ${{ inputs.spellcheck }}
          task_name: Markdown
